# JIRA startup script - adapted from: http://confluence.atlassian.com/display/JIRA/Starting+JIRA+Automatically+on+Linux
#chkconfig: 2345 80 05
#description: Atlassian Confluence

### BEGIN INIT INFO
# Provides:          Confluence
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop Atlassian Confluence standalone server
### END INIT INFO

# Define some variables
# Name of app ( JIRA, Confluence, etc )
APP=atlassian-confluence
# Name of the user to run as
USER=confluence
# Location of application's base directory
BASE=/opt/confluence

start() {
  echo "Starting $APP"
  su -l $USER -c $BASE/bin/start-confluence.sh
  return $?
}

stop() {
  echo "Stopping $APP"
  su -l $USER -c $BASE/bin/stop-confluence.sh
  return $?
}

case "$1" in
  # Start command
  start)
    start
    RETVAL=$?
    ;;
  # Stop command
  stop)
    stop
    RETVAL=$?
    ;;
  # Restart command
  restart)
    stop
    start
    RETVAL=$?
    ;;
  # Status command
  status)
    status_of_proc -p $BASE/work/catalina.pid $BASE/jre/bin/java $APP
    RETVAL=$?
    ;;
  *)
    echo "Usage: $APP {start|restart|stop|status}"
    RETVAL=2
    ;;
esac
 
exit $RETVAL
